import {
  BTCLogo,
  ETHLogo,
  JSTLogo,
  NFTLogo,
  OSKLogo,
  SafeMoneyLogo,
  SUNLogo,
  TRXLogo,
  TUSDLogo,
  USDCLogo,
  USDJLogo,
  WBTTLogo,
  WINLogo,
  RickLogo,
  GskLogo,
  PnLogo,
  BtzcLogo,
  NdwLogo,
  AcvtLogo,
  DiceLogo,
  LiveLogo,
} from '../assets/icons/tokens';
import { TypeToken } from '../types';

import { isProduction } from './index';

export const tokenList: TypeToken[] = isProduction
  ? [
      {
        name: 'TRX',
        symbol: 'TRX',
        address: '',
        decimals: 6,
        logo: TRXLogo,
      },
      {
        name: 'SafeMoney',
        symbol: 'SM',
        address: 'TNBrVEzuVYbNbGF2ua3ivSX5Y5V9N4xhax',
        decimals: 8,
        logo: SafeMoneyLogo,
      },
      {
        name: 'OSK',
        symbol: 'OSK',
        address: 'TDk91SWz2GvwfZwMTGX21d4ngUUH8YZZAv',
        decimals: 18,
        logo: OSKLogo,
      },
      {
        name: 'Wrapped BitTorrent',
        symbol: 'WBTT',
        address: 'TKfjV9RNKJJCqPvBtK8L7Knykh7DNWvnYt',
        decimals: 6,
        logo: WBTTLogo,
      },
      {
        name: 'BTT New',
        symbol: 'BTT',
        address: 'TAFjULxiVgT4qWk6UZwjqwZXTSaGaqnVp4',
        decimals: 18,
        logo: WBTTLogo,
      },
      {
        name: 'JUST GOV v1.0',
        symbol: 'JST',
        address: 'TCFLL5dx5ZJdKnWuesXxi1VPwjLVmWZZy9',
        decimals: 18,
        logo: JSTLogo,
      },
      {
        name: 'Bitcoin',
        symbol: 'BTC',
        address: 'TN3W4H6rK2ce4vX9YnFQHwKENnHjoxb3m9',
        decimals: 8,
        logo: BTCLogo,
      },
      {
        name: 'JUST Stablecoin v1.0',
        symbol: 'USDJ',
        address: 'TMwFHYXLJaRUPeW6421aqXL4ZEzPRFGkGT',
        decimals: 18,
        logo: USDJLogo,
      },
      {
        name: 'GoldenSpark',
        symbol: 'GSK',
        address: 'TTtVBQ75mnW3XNvUKTDUKMS3QMfjoz11CK',
        decimals: 6,
        logo: GskLogo,
      },
      {
        name: 'SUN TOKEN',
        symbol: 'SUN',
        address: 'TSSMHYeV2uE9qYH95DqyoCuNCzEL1NvU3S',
        decimals: 18,
        logo: SUNLogo,
      },
      {
        name: 'WINK',
        symbol: 'WIN',
        address: 'TLa2f6VPqDgRE67v1736s7bJ8Ray5wYjU7',
        decimals: 6,
        logo: WINLogo,
      },
      {
        name: 'TrueUSD',
        symbol: 'TUSD',
        address: 'TUpMhErZL2fhh4sVNULAbNKLokS4GjC1F4',
        decimals: 18,
        logo: TUSDLogo,
      },
      {
        name: 'APENFT',
        symbol: 'NFT',
        address: 'TFczxzPhnThNSqr5by8tvxsdCFRRz6cPNq',
        decimals: 6,
        logo: NFTLogo,
      },
      {
        name: 'USD Coin',
        symbol: 'USDC',
        address: 'TEkxiTehnzSmSe2XqrBj4w32RUN966rdz8',
        decimals: 6,
        logo: USDCLogo,
      },
      {
        name: 'Ethereum',
        symbol: 'ETH',
        address: 'THb4CqiFdwNHsWsQCs4JhzwjMWys4aqCbF',
        decimals: 18,
        logo: ETHLogo,
      },
      {
        name: 'Infinite Ricks',
        symbol: 'RICK',
        address: 'TDk5875Key1Yu2TxWy5W5EogUP86r7Jhxd',
        decimals: 6,
        logo: RickLogo,
      },
      {
        name: 'NDW',
        symbol: 'NDW',
        address: 'TCdB7kBa2TFng6Kc57Uf6ai2psBGi5zyij',
        decimals: 6,
        logo: NdwLogo,
      },
      {
        name: 'BeatzCoin',
        symbol: 'BTZC',
        address: 'TNsnPquPbEo6zCYSB9mZbrnSogyJ3cksNo',
        decimals: 6,
        logo: BtzcLogo,
      },
      {
        name: 'PN',
        symbol: 'PN',
        address: 'TDxbHVxtpDoJJ5bnG6xJHc1ezJK5Zuuw2S',
        decimals: 6,
        logo: PnLogo,
      },
      {
        name: 'ActivEightCoin',
        symbol: 'ACTIV',
        address: 'TVoxBVmFuBM7dsRnfi1V8v1iupv4uyPifN',
        decimals: 8,
        logo: AcvtLogo,
      },
      {
        name: 'TRONbetDice',
        symbol: 'DICE',
        address: 'TKttnV3FSY1iEoAwB4N52WK2DxdV94KpSd',
        decimals: 6,
        logo: DiceLogo,
      },
      {
        name: 'TRONbetLive',
        symbol: 'LIVE',
        address: 'TVgAYofpQku5G4zenXnvxhbZxpzzrk8WVK',
        decimals: 6,
        logo: LiveLogo,
      },
    ]
  : [
      {
        name: 'TRX',
        symbol: 'TRX',
        address: '',
        decimals: 6,
        logo: TRXLogo,
      },
      {
        name: 'Solana',
        symbol: 'SOL',
        address: 'TMCtbHNYWavDHBPEcJvDij6uAUU3cHq5xJ',
        decimals: 18,
        logo: TRXLogo,
      },
      {
        name: 'Cardano',
        symbol: 'ADA',
        address: 'TSk6XgRK6k9Y9nwcLx3ZJXf4XA9eurtceK',
        decimals: 18,
        logo: TRXLogo,
      },
      {
        name: 'DOGE',
        symbol: 'DOGE',
        address: 'TDNSKtL8vSWeGPFGm9TymtJptqNcotBWHG',
        decimals: 18,
        logo: TRXLogo,
      },
    ];
